openapi: 3.0.0
info:
  version: '1.0'
  title: "divents OpenAPI"
  description: API to manage events.
  license:
    name: MIT
servers:
  - url: http://localhost:3000/
paths:
  /events:
    x-summary: Events Manager
    get:
      summary: getEventsList
      responses:
        '200':
          description: 'Collection of events'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
components:
  schemas:
    Event:
      type: object
      required:
        - author
        - title
        - brief_descr
        - detailed_descr
        - requirements
        - key_words
        - location_name
        - address
        - latitude
        - longitude
        - date
        - photos
        - max_subscribers
        - subscribers
        - partecipants
      properties:
        author:
          type: string
          description: 'ID of the creator'
        title:
          type: string
          description: 'Name of the event'
        brief_descr:
          type: string
          description: 'Brief description of the event'
        detailed_descr:
          type: string
          description: 'Detailed description of the event'
        requirements:
          type: string
          description: 'Requirements to access the event'
        key_words:
          type: array
          description: 'List of key words of the event'
        location_name:
          type: string
          description: 'Name of the location of the event'
        address:
          type: string
          description: 'Address where the event takes place'
        latitude:
          type: string
          description: 'Latitude where the event takes place'
        longitude:
          type: string
          description: 'Longitude where the event takes place'
        date:
          type: string
          description: 'Date when the event takes place'
        photos:
          type: array
          description: 'Photo of the location'
        max_subscribers:
          type: integer
          description: 'Numbers of allowed partecipants to the event'
        subscribers:
          type: array
          description: 'List of users who have registered for the event'
        partecipants:
          type: array
          description: 'List of users who have joined the event'